config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update, :index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true
  has_many :messages

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  #::はnamespace。rubyのクラスをつなげる
  def index
    @group = Group.find(params[:group_id])
    #Groupモデルからgroup.idを見つけてGroup変数にいれる
    respond_to do |format|
      format.html
      format.json { @new_message = @group.messages.includes(:user).where('id > ?', params[:id]) }
      #メッセージ変数の中でidがあるものについてをnewmessage変数にいれる
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production? # ”if: :production?”と記述することによって、本番環境のみでbasic_authメソッドが実行される
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
  private

  # production?というメソッドを定義し、現在の環境が本番環境ならtrue、そうでないならfalseを返す
  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def edit
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to root_path,notice: 'グループ名を編集しました'
      else
        render :edit
    end
  end
  
  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params) # messageインスタンスの生成
    @message.user_id = current_user.id
    if @message.save #もしMessageインスタンスを保存できたら
      respond_to do |format|
        format.html { redirect_to group_messages_path (params[:group_id])}  # リクエストがHTML形式であればリダイレクト
        format.json     #リクエストがJson形式であればリダイレクト
      end
    else 
      flash[:notice] = "メッセージを入力してください"
      redirect_to group_messages_path(params[:group_id])
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group #Messageインスタンスにgroupのアソシエーションをつける
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit  # editアクションのviewを表示
    end
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      flash.now[:alert] = "グループ名を入力してください"
      render :new
    end
  end

  def index
    #paramsとして送られてきたkeyword（入力された語句）で、Userモデルのnameカラムを検索し、その結果を@usersに代入する
    @users = User.where('name LIKE(?)', "%#{params[:name]}%").where.not(id:current_user.id) #idがcurrent_user.id以外のユーザーを全て取得
    respond_to do |format| 
      format.html
      format.json
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

# The former(require) is used to mark parameters as required. The latter(permit) is used to set the parameter as permitted and limit which attributes should be allowed for mass updating.

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      =f.label :チャットメンバーを追加, class:'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
      //User検索箇所
      %input#user-search-field.chat-group-form__input{ placeholder:'追加したいユーザー名を入力してください', type:'text'}
      //検索結果？ 
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      =f.label :チャットメンバー, class: 'chat-group-form__label'
    .chat-group-form__field--right
      //appendProduct
      #chat-group-users
        - group.users.each do |user|
          .chat-group-user.clearfix{id: "chat-group-user-#{user.id}"}
            = hidden_field_tag "group[user_ids][]", user.id
            %p.chat-group-user__name #{user.name}
            - if current_user.name == user.name
              .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
            - else
              .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
 =render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_flash.html.haml
.flash
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/flash'
    = yield

app/views/messages/_message.html.haml
.message{ data: { id: message.id } }
  .upper-info
    .upper-info__user
      = message.user.name
    .upper-info__date
      = message.created_at.strftime("%Y/%m/%d(%a) %H:%M")
  .lower-info
    - if message.content.present?
      %p.lower-info__text
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?


-# HTML/HAMLのタグ内に[data- 任意の名前 = 任意の値 ] とするとjavascriptから値を引っ張ってこれる。HTMLだとdate-message_id: (#message.id) となる？

app/views/messages/index.html.haml
.flash-box
.wrapper
  = render partial: "shared/side_bar"                                              
  .main-content
    .main-header
      .current-group
        .current-group__name
          = @group.name
        %ul.member-list
          Member：
          %li.member-list__member
            - @group.users.each do |group_user|
              = group_user.name
      .main-header__edit-box
        .main-header__edit-btn 
          = link_to edit_group_path(@group.id) do
            Edit

    .messages
      = render @messages  
            
    .form
      = form_for [@group, @message] do |f|
        .input-box
          .input-box__text
            = f.text_field :content, placeholder: 'type a message'
          .input-box__image
            = f.label :image do 
              = fa_icon 'picture-o', class: 'icon'
              = f.file_field :image, {style: "display:none;"}
        = f.submit 'Send', class: 'submit-btn__image'

app/views/shared/_side_bar.html.haml
.side-bar
  .side-header
    %p.side-header__user-name 
      = current_user.name
    %ul.user-menu
      %li.user-menu__new-group
        = link_to new_group_path do
          = fa_icon 'pencil-square-o fw', class: 'icon'
          
      %li.user-menu__edit-user
        = link_to edit_user_path(current_user) do
          = fa_icon 'cog fw', class: 'icon'
  .groups
    - current_user.groups.each do |group|
      .group
        = link_to group_messages_path(group) do
          .group__name
            = group.name
          .group__message
            = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'